# Generated by Django 5.2.7 on 2025-11-03 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been archived (soft deleted)",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when this record was archived",
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique course code (e.g., 'BSCS', 'BSBA')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full course name (e.g., 'Bachelor of Science in Computer Science')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the academic program",
                    ),
                ),
                (
                    "total_units",
                    models.PositiveIntegerField(
                        help_text="Total units required to graduate from this program",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "years_to_complete",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Expected number of years to complete the program",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Course (Degree Program)",
                "verbose_name_plural": "Courses (Degree Programs)",
                "ordering": ["code"],
            },
        ),
    ]
