# Generated by Django 5.2.7 on 2025-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("ARCHIVE", "Archive"),
                            ("RESTORE", "Restore"),
                            ("DELETE", "Delete"),
                            ("POLICY_EXPIRE", "Policy Expire"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Name of the affected database table", max_length=100
                    ),
                ),
                (
                    "record_id",
                    models.IntegerField(help_text="ID of the affected record"),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True,
                        help_text="Previous state of the record (for updates)",
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="New state of the record", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was performed"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the actor", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser/client user agent", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
