# Generated by Django 5.2.7 on 2025-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("ARCHIVE", "Archive"),
                            ("RESTORE", "Restore"),
                            ("DELETE", "Delete"),
                            ("POLICY_EXPIRE", "Policy Expire"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Model/table name (e.g., 'students.Student')",
                        max_length=100,
                    ),
                ),
                (
                    "record_id",
                    models.IntegerField(help_text="Primary key of the affected record"),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True,
                        help_text="Previous state (for UPDATE/ARCHIVE)",
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True,
                        help_text="New state (for CREATE/UPDATE/RESTORE)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
