[tool:pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = 
    --verbose
    --cov=richwell_portal
    --cov-report=html
    --cov-report=term-missing
    --ds=config.settings.test
testpaths = tests
