# Generated by Django 5.2.7 on 2025-11-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "0001_initial"),
        ("sections", "0001_initial"),
        ("students", "0001_initial"),
        ("subjects", "0001_initial"),
        ("terms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrolled_by",
            field=models.ForeignKey(
                help_text="Staff who processed the enrollment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned section (nullable for irregular students)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="sections.section",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="Enrolled student",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject enrolled in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="term",
            field=models.ForeignKey(
                help_text="Academic term",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="terms.term",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "term", "archived"],
                name="enrollments_student_df568a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["section", "archived"], name="enrollments_section_caf43e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="enrollments_status_48622c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "subject", "term")},
        ),
    ]
