# Generated by Django for RCI testing and quality suite

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        # Add composite indexes for common enrollment query patterns
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(
                fields=['student', 'term', 'status'],
                name='enroll_student_term_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(
                fields=['section', 'status'],
                name='enroll_section_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(
                fields=['term', 'status', 'archived'],
                name='enroll_term_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(
                fields=['student', 'archived'],
                name='enroll_student_arch_idx'
            ),
        ),
    ]
