# Generated by Django 5.2.7 on 2025-11-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_initial"),
        ("sections", "0002_initial"),
        ("students", "0002_initial"),
        ("subjects", "0002_initial"),
        ("terms", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "ordering": ["-term", "student", "subject"],
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
            },
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Class section (nullable for irregular students)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="sections.section",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Current enrollment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="The student enrolling in the subject",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="subject",
            field=models.ForeignKey(
                help_text="The subject being enrolled in",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="subjects.subject",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="term",
            field=models.ForeignKey(
                help_text="The academic term for this enrollment",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="terms.term",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="units",
            field=models.PositiveIntegerField(
                help_text="Credit units (copied from subject for audit purposes)"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "term", "status"],
                name="enrollments_student_a0be44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["section", "archived"], name="enrollments_section_caf43e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["term", "status"], name="enrollments_term_id_55ad18_idx"
            ),
        ),
    ]
