# Generated by Django 5.2.7 on 2025-11-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enroll_student_term_idx",
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enroll_section_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enroll_term_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enroll_student_arch_idx",
        ),
    ]
