# Generated by Django 5.2.7 on 2025-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student_id",
                    models.CharField(
                        help_text="Unique student ID number", max_length=20, unique=True
                    ),
                ),
                (
                    "year_level",
                    models.PositiveIntegerField(
                        default=1, help_text="Current year level (1-4)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("GRADUATED", "Graduated"),
                            ("DROPPED", "Dropped"),
                            ("LOA", "Leave of Absence"),
                        ],
                        default="ACTIVE",
                        help_text="Current enrollment status",
                        max_length=20,
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Student documents (JSON field for future CDN/S3 URLs)",
                    ),
                ),
                (
                    "date_enrolled",
                    models.DateField(
                        blank=True, help_text="Date first enrolled", null=True
                    ),
                ),
                (
                    "date_graduated",
                    models.DateField(
                        blank=True,
                        help_text="Date graduated (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, help_text="Student contact number", max_length=20
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Student address")),
            ],
            options={
                "ordering": ["student_id"],
            },
        ),
    ]
