# Generated by Django 5.2.7 on 2025-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student_id",
                    models.CharField(
                        help_text="Student ID number", max_length=20, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("IRREGULAR", "Irregular"),
                            ("LOA", "Leave of Absence"),
                            ("GRADUATED", "Graduated"),
                            ("DROPPED", "Dropped"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "year_level",
                    models.PositiveIntegerField(
                        default=1, help_text="Current year level (1-4)"
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Document metadata (birth cert, form 137, etc.)",
                    ),
                ),
            ],
            options={
                "ordering": ["student_id"],
            },
        ),
    ]
