# Generated by Django 5.2.7 on 2025-11-04 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("students", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["student_id"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                help_text="The degree program the student is enrolled in",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="documents",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Document metadata (birth certificate, form 137, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("IRREGULAR", "Irregular"),
                    ("LOA", "Leave of Absence"),
                    ("GRADUATED", "Graduated"),
                    ("DROPPED", "Dropped"),
                ],
                db_index=True,
                default="ACTIVE",
                help_text="Current academic status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique student ID number (e.g., '2024-001')",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="Link to user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_level",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Current year level (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["student_id", "archived"], name="students_st_student_fad7e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["course", "year_level"], name="students_st_course__bf4c4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["status", "archived"], name="students_st_status_7de6c2_idx"
            ),
        ),
    ]
