# Generated by Django for RCI testing and quality suite

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options_alter_student_course_and_more'),
    ]

    operations = [
        # Add composite indexes for common query patterns
        migrations.AddIndex(
            model_name='student',
            index=models.Index(
                fields=['status', 'archived'],
                name='student_status_arch_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(
                fields=['user', 'archived'],
                name='student_user_arch_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(
                fields=['student_id'],
                name='student_id_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(
                fields=['created_at', 'archived'],
                name='student_created_arch_idx'
            ),
        ),
    ]
