# Generated by Django 5.2.7 on 2025-11-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="student",
            name="student_status_arch_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_user_arch_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_created_arch_idx",
        ),
    ]
