# Generated by Django 5.2.7 on 2025-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1.0", "1.0 (Excellent)"),
                            ("1.5", "1.5"),
                            ("2.0", "2.0"),
                            ("2.5", "2.5"),
                            ("3.0", "3.0 (Passing)"),
                            ("5.0", "5.0 (Failed)"),
                            ("INC", "Incomplete"),
                            ("DRP", "Dropped"),
                        ],
                        help_text="Encoded grade",
                        max_length=10,
                    ),
                ),
                (
                    "encoded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the grade was encoded"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Additional remarks or notes"
                    ),
                ),
            ],
            options={
                "ordering": ["-encoded_at"],
            },
        ),
        migrations.CreateModel(
            name="INCRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateField(help_text="Deadline to resolve the INC")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the INC was resolved", null=True
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True, help_text="Notes about INC resolution"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, help_text="Whether the INC has expired"
                    ),
                ),
            ],
            options={
                "ordering": ["deadline"],
            },
        ),
    ]
