# Generated by Django 5.2.7 on 2025-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1.0", "1.0"),
                            ("1.5", "1.5"),
                            ("2.0", "2.0"),
                            ("2.5", "2.5"),
                            ("3.0", "3.0"),
                            ("5.0", "5.0 (Failed)"),
                            ("INC", "Incomplete"),
                            ("DRP", "Dropped"),
                        ],
                        max_length=5,
                    ),
                ),
                ("encoded_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-encoded_at"],
            },
        ),
        migrations.CreateModel(
            name="INCRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deadline",
                    models.DateField(
                        help_text="Deadline to complete requirements (6 or 12 months)"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_note",
                    models.TextField(blank=True, help_text="How the INC was resolved"),
                ),
            ],
            options={
                "ordering": ["deadline"],
            },
        ),
    ]
