# Generated by Django 5.2.7 on 2025-11-04 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "0002_initial"),
        ("grades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="graderecord",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graderecord",
            name="encoded_by",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROFESSOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encoded_grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graderecord",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade",
                to="enrollments.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="increcord",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="increcord",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "REGISTRAR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_incs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="increcord",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inc_record",
                to="enrollments.enrollment",
            ),
        ),
    ]
