# Generated by Django 5.2.7 on 2025-11-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "0002_initial"),
        ("grades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="graderecord",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graderecord",
            name="encoded_by",
            field=models.ForeignKey(
                help_text="Professor who encoded the grade",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encoded_grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graderecord",
            name="enrollment",
            field=models.OneToOneField(
                help_text="Associated enrollment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade",
                to="enrollments.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="increcord",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Registrar who confirmed resolution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_incs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="increcord",
            name="enrollment",
            field=models.OneToOneField(
                help_text="Associated enrollment with INC grade",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inc_record",
                to="enrollments.enrollment",
            ),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(
                fields=["enrollment", "archived"], name="grades_grad_enrollm_c0eb42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(fields=["grade"], name="grades_grad_grade_53786b_idx"),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(
                fields=["-encoded_at"], name="grades_grad_encoded_3c5bc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="increcord",
            index=models.Index(
                fields=["deadline", "resolved_at"],
                name="grades_incr_deadlin_d7e2c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="increcord",
            index=models.Index(
                fields=["expired"], name="grades_incr_expired_be787a_idx"
            ),
        ),
    ]
