# Generated by Django 5.2.7 on 2025-11-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enrollments",
            "0003_alter_enrollment_options_alter_enrollment_section_and_more",
        ),
        ("grades", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="graderecord",
            options={
                "ordering": ["-encoded_at"],
                "verbose_name": "Grade Record",
                "verbose_name_plural": "Grade Records",
            },
        ),
        migrations.AlterModelOptions(
            name="increcord",
            options={
                "ordering": ["deadline"],
                "verbose_name": "INC Record",
                "verbose_name_plural": "INC Records",
            },
        ),
        migrations.AlterField(
            model_name="graderecord",
            name="encoded_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the grade was encoded"
            ),
        ),
        migrations.AlterField(
            model_name="graderecord",
            name="encoded_by",
            field=models.ForeignKey(
                help_text="Professor who encoded this grade",
                limit_choices_to={"role": "PROFESSOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encoded_grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="graderecord",
            name="enrollment",
            field=models.OneToOneField(
                help_text="The enrollment this grade belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade",
                to="enrollments.enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="graderecord",
            name="grade",
            field=models.CharField(
                choices=[
                    ("1.0", "1.0 (Excellent)"),
                    ("1.5", "1.5 (Very Good)"),
                    ("2.0", "2.0 (Good)"),
                    ("2.5", "2.5 (Satisfactory)"),
                    ("3.0", "3.0 (Passing)"),
                    ("5.0", "5.0 (Failed)"),
                    ("INC", "Incomplete"),
                    ("DRP", "Dropped"),
                ],
                help_text="Final grade for the enrollment",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="graderecord",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Additional comments or notes about the grade"
            ),
        ),
        migrations.AlterField(
            model_name="increcord",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Registrar who confirmed the resolution",
                limit_choices_to={"role": "REGISTRAR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_incs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="increcord",
            name="enrollment",
            field=models.OneToOneField(
                help_text="The enrollment with INC grade",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inc_record",
                to="enrollments.enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="increcord",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the INC was resolved", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(
                fields=["enrollment", "archived"], name="grades_grad_enrollm_c0eb42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(
                fields=["grade", "encoded_at"], name="grades_grad_grade_5ce334_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graderecord",
            index=models.Index(
                fields=["encoded_by", "encoded_at"],
                name="grades_grad_encoded_c5d2f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="increcord",
            index=models.Index(
                fields=["deadline", "resolved_at"],
                name="grades_incr_deadlin_d7e2c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="increcord",
            index=models.Index(
                fields=["enrollment", "archived"], name="grades_incr_enrollm_a7228f_idx"
            ),
        ),
    ]
