# Generated by Django for RCI testing and quality suite

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_graderecord_options_alter_increcord_options_and_more'),
    ]

    operations = [
        # Add composite indexes for common grade query patterns
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(
                fields=['enrollment', 'archived'],
                name='grade_enrollment_arch_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(
                fields=['grade', 'archived'],
                name='grade_value_arch_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(
                fields=['encoded_by', 'encoded_at'],
                name='grade_encoder_time_idx'
            ),
        ),
        # Add indexes for INC record queries
        migrations.AddIndex(
            model_name='increcord',
            index=models.Index(
                fields=['deadline', 'resolved_at'],
                name='inc_deadline_resolved_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='increcord',
            index=models.Index(
                fields=['enrollment', 'archived'],
                name='inc_enrollment_arch_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='increcord',
            index=models.Index(
                fields=['resolved_at', 'deadline'],
                name='inc_resolved_deadline_idx'
            ),
        ),
    ]
