# Generated by Django for RCI testing and quality suite

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_increcord_completion_date_and_more'),
    ]

    operations = [
        # Add composite indexes for common grade query patterns
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(
                fields=['student', 'term', 'archived'],
                name='grade_student_term_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(
                fields=['subject', 'term'],
                name='grade_subject_term_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(
                fields=['grade', 'archived'],
                name='grade_value_arch_idx'
            ),
        ),
        # Add indexes for INC record queries
        migrations.AddIndex(
            model_name='increcord',
            index=models.Index(
                fields=['status', 'deadline_date'],
                name='inc_status_deadline_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='increcord',
            index=models.Index(
                fields=['deadline_date', 'status'],
                name='inc_deadline_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='increcord',
            index=models.Index(
                fields=['grade_record', 'status'],
                name='inc_grade_status_idx'
            ),
        ),
    ]
