# Generated by Django 5.2.7 on 2025-11-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="graderecord",
            name="grade_student_term_idx",
        ),
        migrations.RemoveIndex(
            model_name="graderecord",
            name="grade_subject_term_idx",
        ),
        migrations.RemoveIndex(
            model_name="graderecord",
            name="grade_value_arch_idx",
        ),
        migrations.RemoveIndex(
            model_name="increcord",
            name="inc_status_deadline_idx",
        ),
        migrations.RemoveIndex(
            model_name="increcord",
            name="inc_deadline_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="increcord",
            name="inc_grade_status_idx",
        ),
    ]
