# Generated by Django 5.2.7 on 2025-11-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_add_performance_indexes"),
    ]

    operations = [
        # Remove indexes created in 0004_add_performance_indexes
        migrations.RemoveIndex(
            model_name="graderecord",
            name="grade_enrollment_arch_idx",
        ),
        migrations.RemoveIndex(
            model_name="graderecord",
            name="grade_value_arch_idx",
        ),
        migrations.RemoveIndex(
            model_name="graderecord",
            name="grade_encoder_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="increcord",
            name="inc_deadline_resolved_idx",
        ),
        migrations.RemoveIndex(
            model_name="increcord",
            name="inc_enrollment_arch_idx",
        ),
        migrations.RemoveIndex(
            model_name="increcord",
            name="inc_resolved_deadline_idx",
        ),
    ]
