# Generated by Django for RCI testing and quality suite

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        # Add composite indexes for common user query patterns
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['role', 'is_active', 'archived'],
                name='user_role_active_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['username', 'is_active'],
                name='user_username_active_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['email', 'is_active'],
                name='user_email_active_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['archived', 'archived_at'],
                name='user_archived_at_idx'
            ),
        ),
    ]
