# Generated by Django 5.2.7 on 2025-11-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="user_role_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_username_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_email_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_archived_at_idx",
        ),
    ]
