# Generated by Django 5.2.7 on 2025-11-06 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been archived (soft deleted)",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when this record was archived",
                        null=True,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INC_REMINDER", "INC Deadline Reminder"),
                            ("GRADE_POSTED", "Grade Posted"),
                            ("ENROLLMENT_CONFIRMED", "Enrollment Confirmed"),
                            ("SECTION_ASSIGNED", "Section Assigned"),
                            ("GENERAL", "General Notification"),
                        ],
                        default="GENERAL",
                        help_text="Type of notification",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message body")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL to related resource (optional)",
                        max_length=500,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether notification has been read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was read", null=True
                    ),
                ),
                (
                    "sent_via_email",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this notification was sent via email",
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When email was sent", null=True
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (e.g., 'inc_record', 'grade_record')",
                        max_length=50,
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who archived this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User receiving this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "archived"],
                        name="notificatio_recipie_9ea93a_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                    models.Index(
                        fields=["sent_via_email", "email_sent_at"],
                        name="notificatio_sent_vi_9bbd16_idx",
                    ),
                ],
            },
        ),
    ]
