# Generated by Django 5.2.7 on 2025-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_year",
                    models.CharField(
                        help_text="Academic year (e.g., 2024-2025)", max_length=20
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1ST", "1st Semester"),
                            ("2ND", "2nd Semester"),
                            ("SUMMER", "Summer"),
                        ],
                        help_text="Semester type",
                        max_length=10,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Only one term can be active at a time"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Start date of the term", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date of the term", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-school_year", "-semester"],
                "indexes": [
                    models.Index(
                        fields=["active"], name="terms_term_active_e81535_idx"
                    ),
                    models.Index(
                        fields=["-school_year"], name="terms_term_school__11874f_idx"
                    ),
                ],
                "unique_together": {("school_year", "semester")},
            },
        ),
    ]
