# Generated by Django 5.2.7 on 2025-11-03 13:10
# Generated by Django 5.2.7 on 2025-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_year",
                    models.CharField(
                        help_text="Format: YYYY-YYYY (e.g., 2024-2025)", max_length=20
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Semester"),
                            ("SECOND", "Second Semester"),
                            ("SUMMER", "Summer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Only one term can be active at a time"
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been archived (soft deleted)",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when this record was archived",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Term name (e.g., 'Fall 2024', 'Spring 2025')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (auto-generated from name)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("term_start", models.DateField(help_text="First day of classes")),
                ("term_end", models.DateField(help_text="Last day of classes")),
                (
                    "enrollment_start",
                    models.DateField(help_text="When enrollment opens for this term"),
                ),
                (
                    "enrollment_end",
                    models.DateField(help_text="Last day students can enroll"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this is the current enrollment term",
                    ),
                ),
            ],
            options={
                "ordering": ["-school_year", "-semester"],
                "unique_together": {("school_year", "semester")},
                "verbose_name": "Academic Term",
                "verbose_name_plural": "Academic Terms",
                "ordering": ["-term_start"],
            },
        ),
    ]
