# Generated by Django 5.2.7 on 2025-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_year",
                    models.CharField(
                        help_text="Format: YYYY-YYYY (e.g., 2024-2025)", max_length=20
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Semester"),
                            ("SECOND", "Second Semester"),
                            ("SUMMER", "Summer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Only one term can be active at a time"
                    ),
                ),
            ],
            options={
                "ordering": ["-school_year", "-semester"],
                "unique_together": {("school_year", "semester")},
            },
        ),
    ]
