# Generated by Django 5.2.7 on 2025-11-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("terms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["term_start", "term_end"], name="terms_term_term_st_6c5985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["enrollment_start", "enrollment_end"],
                name="terms_term_enrollm_6d822a_idx",
            ),
        ),
    ]
