# Generated by Django 5.2.7 on 2025-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssignedSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Class schedule (e.g., MWF 9:00-10:00 AM)",
                        max_length=200,
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, help_text="Room assignment", max_length=50
                    ),
                ),
            ],
            options={
                "ordering": ["section", "subject"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Section code (e.g., BSIT-1A, BSEd-2B)", max_length=20
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=40, help_text="Maximum number of students"
                    ),
                ),
                (
                    "slots_remaining",
                    models.PositiveIntegerField(
                        default=40, help_text="Available enrollment slots"
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
