# Generated by Django 5.2.7 on 2025-11-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("sections", "0001_initial"),
        ("subjects", "0001_initial"),
        ("terms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedsubject",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignedsubject",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                help_text="Professor teaching this subject",
                limit_choices_to={"role": "PROFESSOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignedsubject",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject being taught",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                help_text="Section adviser (Professor)",
                limit_choices_to={"role": "PROFESSOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advised_sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                help_text="Associated course/program",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="term",
            field=models.ForeignKey(
                help_text="Academic term",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="terms.term",
            ),
        ),
        migrations.AddField(
            model_name="assignedsubject",
            name="section",
            field=models.ForeignKey(
                help_text="Section this subject is assigned to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_subjects",
                to="sections.section",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["course", "term", "archived"],
                name="sections_se_course__beacf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["term", "year_level"], name="sections_se_term_id_c4d6b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("code", "term")},
        ),
        migrations.AddIndex(
            model_name="assignedsubject",
            index=models.Index(
                fields=["section", "archived"], name="sections_as_section_fa8886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignedsubject",
            index=models.Index(
                fields=["professor", "archived"], name="sections_as_profess_dd2bc6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignedsubject",
            unique_together={("section", "subject")},
        ),
    ]
