# Generated by Django 5.2.7 on 2025-11-04 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("sections", "0001_initial"),
        ("subjects", "0001_initial"),
        ("terms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedsubject",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignedsubject",
            name="professor",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROFESSOR"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignedsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="terms.term",
            ),
        ),
        migrations.AddField(
            model_name="assignedsubject",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_subjects",
                to="sections.section",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("code", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="assignedsubject",
            unique_together={("section", "subject")},
        ),
    ]
