# Generated by Django 5.2.7 on 2025-11-04 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("sections", "0002_initial"),
        ("subjects", "0002_initial"),
        ("terms", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignedsubject",
            options={
                "ordering": ["section", "subject"],
                "verbose_name": "Assigned Subject",
                "verbose_name_plural": "Assigned Subjects",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["code"],
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
            },
        ),
        migrations.AlterField(
            model_name="assignedsubject",
            name="professor",
            field=models.ForeignKey(
                help_text="The professor teaching this subject",
                limit_choices_to={"role": "PROFESSOR"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teaching_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assignedsubject",
            name="room",
            field=models.CharField(
                blank=True,
                help_text="Room assignment (e.g., 'Room 301', 'Lab A')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assignedsubject",
            name="schedule",
            field=models.CharField(
                blank=True,
                help_text="Class schedule (e.g., 'MWF 9:00-10:00 AM', 'TTh 1:00-2:30 PM')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="assignedsubject",
            name="section",
            field=models.ForeignKey(
                help_text="The section this subject is assigned to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_subjects",
                to="sections.section",
            ),
        ),
        migrations.AlterField(
            model_name="assignedsubject",
            name="subject",
            field=models.ForeignKey(
                help_text="The subject being taught",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="subjects.subject",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="capacity",
            field=models.PositiveIntegerField(
                default=40,
                help_text="Maximum number of students (minimum 10)",
                validators=[django.core.validators.MinValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Section code (e.g., 'BSIT-1A', 'BSEd-2B')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                help_text="The degree program this section belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="term",
            field=models.ForeignKey(
                help_text="The academic term for this section",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="terms.term",
            ),
        ),
        migrations.AddIndex(
            model_name="assignedsubject",
            index=models.Index(
                fields=["section", "archived"], name="sections_as_section_fa8886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignedsubject",
            index=models.Index(
                fields=["professor", "archived"], name="sections_as_profess_dd2bc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignedsubject",
            index=models.Index(
                fields=["subject", "section"], name="sections_as_subject_8aad99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["code", "term", "archived"], name="sections_se_code_4672a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["course", "term"], name="sections_se_course__9315c7_idx"
            ),
        ),
    ]
