# Generated by Django 5.2.7 on 2025-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Subject code (e.g., CS101, MATH101)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Subject title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Subject description"),
                ),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Number of units (credit hours)",
                        max_digits=3,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("MAJOR", "Major"),
                            ("MINOR", "Minor"),
                            ("GE", "General Education"),
                            ("ELECTIVE", "Elective"),
                        ],
                        default="MAJOR",
                        help_text="Type of subject",
                        max_length=20,
                    ),
                ),
                (
                    "year_level",
                    models.PositiveIntegerField(
                        blank=True, help_text="Recommended year level (1-4)", null=True
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        help_text="Recommended semester (1ST, 2ND, SUMMER)",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
