# Generated by Django 5.2.7 on 2025-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Subject code (e.g., CS101, MATH101)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("units", models.PositiveIntegerField(default=3)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor Subject"),
                            ("MAJOR", "Major Subject"),
                            ("GE", "General Education"),
                        ],
                        default="MINOR",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
