# Generated by Django 5.2.7 on 2025-11-04 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been archived (soft deleted)",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when this record was archived",
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique subject code (e.g., 'COMP101', 'MATH201')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subject name (e.g., 'Introduction to Programming')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the subject content and objectives",
                    ),
                ),
                (
                    "units",
                    models.PositiveIntegerField(
                        help_text="Credit units (typically 1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "year_level",
                    models.PositiveIntegerField(
                        help_text="Academic year level (1=Freshman, 2=Sophomore, etc.)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["course__code", "year_level", "code"],
            },
        ),
    ]
