# Generated by Django 5.2.7 on 2025-11-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="course",
            field=models.ForeignKey(
                help_text="Associated degree program",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Prerequisite subjects",
                related_name="required_for",
                to="subjects.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["code"], name="subjects_su_code_22ddd2_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["course", "archived"], name="subjects_su_course__8ad70a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["subject_type"], name="subjects_su_subject_3f1615_idx"
            ),
        ),
    ]
