# Generated by Django 5.2.7 on 2025-11-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="course",
            field=models.ForeignKey(
                help_text="The degree program this subject belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_set",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects that must be completed before enrolling in this subject",
                related_name="prerequisite_for",
                to="subjects.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["code", "archived"], name="subjects_su_code_480cf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["course", "year_level"], name="subjects_su_course__8bd256_idx"
            ),
        ),
    ]
